version: "3"

services:
  api:
    build:
      context: .
    container_name: user
    ports:
      - 8083:8083
  db:
    container_name: db
    image: postgres:10-alpine3.16
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=user
